# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolutions', '0001_initial'),
        ('faculties', '0001_initial'),
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national', models.IntegerField()),
                ('career', models.IntegerField()),
                ('university', models.IntegerField()),
                ('fkfaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculties.Faculty')),
                ('fkresolution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resolutions.Resolution')),
                ('fkstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statuses.Status')),
                ('fkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
