# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namecareers', '0001_initial'),
        ('careers', '0002_auto_20160729_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='fknamecareer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='namecareers.NameCareer'),
            preserve_default=False,
        ),
    ]
