# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_career_fknamecareer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='name',
        ),
    ]
