# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_remove_career_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='career',
        ),
        migrations.RemoveField(
            model_name='career',
            name='university',
        ),
        migrations.AddField(
            model_name='career',
            name='arcusur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='career',
            name='posgrado',
            field=models.BooleanField(default=False),
        ),
    ]
