# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20160822_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='national',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
