# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeevaluators', '0001_initial'),
        ('namecareers', '0003_auto_20160929_1203'),
        ('evaluators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesEvaluator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'TypeEvaluator',
                'verbose_name_plural': 'TypesEvaluators',
            },
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='curriculum',
            field=models.FileField(blank=True, upload_to='curriculum/%Y_%m_%d/'),
        ),
        migrations.AddField(
            model_name='typesevaluator',
            name='fkevaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators.Evaluator'),
        ),
        migrations.AddField(
            model_name='typesevaluator',
            name='fknamecareer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namecareers.NameCareer'),
        ),
        migrations.AddField(
            model_name='typesevaluator',
            name='fktypeevaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeevaluators.TypeEvaluator'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='evaltypes',
            field=models.ManyToManyField(through='evaluators.TypesEvaluator', to='typeevaluators.TypeEvaluator'),
        ),
    ]
