# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-16 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0002_auto_20161216_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluator',
            options={'ordering': ('id',), 'verbose_name': 'Evaluator', 'verbose_name_plural': 'Evaluators'},
        ),
        migrations.RenameField(
            model_name='evaluator',
            old_name='evaltypes',
            new_name='typesevaluators',
        ),
    ]
