# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_auto_20160729_1054'),
        ('evaluators', '0004_auto_20161219_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='fkstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statuses.Status'),
            preserve_default=False,
        ),
    ]
