# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0005_evaluator_fkstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typesevaluator',
            options={'ordering': ('id',), 'verbose_name': 'Type Evaluator', 'verbose_name_plural': 'Types Evaluators'},
        ),
        migrations.AddField(
            model_name='evaluator',
            name='ci',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluator',
            name='email',
            field=models.EmailField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
