# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalities', '0001_initial'),
        ('evaluators', '0006_auto_20170106_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='fknationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nationalities.Nationality'),
            preserve_default=False,
        ),
    ]
