# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0007_evaluator_fknationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='ci',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='email',
            field=models.EmailField(max_length=140, unique=True),
        ),
    ]
