# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-03 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0008_auto_20170106_1222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typesevaluator',
            unique_together=set([('fkevaluator', 'fktypeevaluator', 'fknamecareer')]),
        ),
    ]
