# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0005_auto_20160729_1336'),
        ('evaluators', '0009_auto_20170203_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='fkresolution',
        ),
        migrations.AddField(
            model_name='typesevaluator',
            name='fkreolution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resolutions.Resolution'),
            preserve_default=False,
        ),
    ]
