# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-06 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0010_auto_20170206_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typesevaluator',
            old_name='fkreolution',
            new_name='fkresolution',
        ),
    ]
