# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_fktypeuniversity'),
        ('evaluators', '0011_auto_20170206_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_job', models.DateField()),
                ('end_job', models.DateField()),
                ('reason', models.TextField()),
                ('doc', models.FileField(blank=True, upload_to='declarations/%Y_%m_%d/')),
            ],
            options={
                'ordering': ('fkuniversity__name',),
                'verbose_name': 'Evaluator / University',
                'verbose_name_plural': 'Evaluators / Universities',
            },
        ),
        migrations.AlterModelOptions(
            name='evaluator',
            options={'ordering': ('ci',), 'verbose_name': 'Evaluator', 'verbose_name_plural': 'Evaluators'},
        ),
        migrations.AlterModelOptions(
            name='typesevaluator',
            options={'ordering': ('fknamecareer__description',), 'verbose_name': 'Type Evaluator', 'verbose_name_plural': 'Types Evaluators'},
        ),
        migrations.AddField(
            model_name='evaluatoruniversity',
            name='fkevaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluators.Evaluator'),
        ),
        migrations.AddField(
            model_name='evaluatoruniversity',
            name='fkuniversity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='conflict',
            field=models.ManyToManyField(through='evaluators.EvaluatorUniversity', to='universities.University'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluatoruniversity',
            unique_together=set([('fkevaluator', 'fkuniversity', 'start_job')]),
        ),
    ]
