# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0012_auto_20170324_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatoruniversity',
            name='end_job',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluatoruniversity',
            name='start_job',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='evaluatoruniversity',
            unique_together=set([('fkevaluator', 'fkuniversity')]),
        ),
    ]
