# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-03 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0013_auto_20170403_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatoruniversity',
            name='end_job',
        ),
        migrations.RemoveField(
            model_name='evaluatoruniversity',
            name='start_job',
        ),
    ]
