# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_auto_20160729_1054'),
        ('evaluators', '0014_auto_20170403_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatoruniversity',
            name='fkstatus',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='statuses.Status'),
            preserve_default=False,
        ),
    ]
