# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecareers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namecareer',
            old_name='namecareer',
            new_name='description',
        ),
    ]
