# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('campuses', '0002_auto_20160729_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='fkdepartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.Department'),
            preserve_default=False,
        ),
    ]
