# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fkcampus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuses.Campus')),
                ('fkuniversity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University')),
            ],
        ),
    ]
