# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_faculty_fkname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
    ]
