# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-06 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=140)),
                ('logs', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('action',),
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audtis',
            },
        ),
    ]
