# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-06 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ('action',), 'verbose_name': 'Audit', 'verbose_name_plural': 'Audits'},
        ),
    ]
