# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-04 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('id',), 'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profiles',
            field=models.ManyToManyField(related_name='user_profile', through='userprofiles.UserProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
