# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolution',
            options={'ordering': ('id',), 'verbose_name': 'Resolution', 'verbose_name_plural': 'Resolutions'},
        ),
        migrations.AlterField(
            model_name='resolution',
            name='document',
            field=models.FileField(upload_to='media/resolutions/'),
        ),
    ]
