# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0004_auto_20160729_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='document',
            field=models.FileField(upload_to='resolutions/%Y_%m_%d/'),
        ),
    ]
