# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
            },
        ),
    ]
