# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeuniversities', '0001_initial'),
        ('universities', '0002_auto_20160729_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='fktypeuniversity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='typeuniversities.TypeUniversity'),
            preserve_default=False,
        ),
    ]
